import 'package:flutter/material.dart';
import '../l10n/app_localizations.dart';
import 'package:google_fonts/google_fonts.dart';

enum LegalType { terms, privacy }

class LegalScreen extends StatelessWidget {
  final LegalType type;
  const LegalScreen({super.key, required this.type});

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;
    final isEn = Localizations.localeOf(context).languageCode == 'en';
    final title = type == LegalType.terms ? l10n.termsTitle : l10n.privacyTitle;
    final content = type == LegalType.terms
        ? (isEn ? _termsEn : _termsFr)
        : (isEn ? _privacyEn : _privacyFr);

    return Scaffold(
      backgroundColor: const Color(0xFF0F172A),
      appBar: AppBar(
        backgroundColor: const Color(0xFF0F172A),
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_ios_new, color: Colors.white, size: 18),
          onPressed: () => Navigator.pop(context),
        ),
        title: Text(title, style: GoogleFonts.inter(
          fontSize: 16, fontWeight: FontWeight.w600, color: Colors.white,
        )),
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.fromLTRB(24, 16, 24, 48),
        child: _LegalContent(markdown: content),
      ),
    );
  }

  // ── Conditions d'utilisation FR ──────────────────────────────────────────

  static const String _termsFr = '''
**Dernière mise à jour : mai 2026**

## 1. Acceptation des conditions

En accédant à l'application Cybrief, vous acceptez les présentes conditions d'utilisation. Si vous n'acceptez pas ces conditions, veuillez ne pas utiliser l'application.

## 2. Description du service

Cybrief est une application de veille en cybersécurité qui fournit des résumés quotidiens d'alertes et de menaces informatiques, générés par intelligence artificielle à partir de sources publiques.

## 3. Abonnement et paiement

**Offre gratuite** : 5 articles par jour, accès limité aux détails techniques.

**Offre Premium** : accès illimité, CVE complets, IOC, alertes critiques en temps réel, newsletter.

Les abonnements sont gérés via Apple App Store ou Google Play Store. Les tarifs en vigueur sont affichés dans l'application. Tout achat est soumis aux conditions de la plateforme concernée.

**Essai gratuit** : 7 jours, résiliable à tout moment avant la fin de la période d'essai sans facturation.

## 4. Propriété intellectuelle

Les résumés générés par Cybrief sont fournis à titre informatif. Les sources originales restent la propriété de leurs auteurs respectifs. Cybrief ne revendique aucun droit sur les contenus tiers cités.

## 5. Limitation de responsabilité

Les informations fournies par Cybrief sont à titre informatif uniquement et ne constituent pas un avis professionnel de sécurité. Cybrief ne peut être tenu responsable de décisions prises sur la base de ces informations.

## 6. Modification des conditions

Cybrief se réserve le droit de modifier ces conditions à tout moment. Les utilisateurs seront notifiés des changements significatifs via l'application.

## 7. Contact

Pour toute question : **hello@cybrief.fr**
''';

  // ── Terms of Use EN ──────────────────────────────────────────────────────

  static const String _termsEn = '''
**Last updated: May 2026**

## 1. Acceptance of Terms

By accessing the Cybrief application, you agree to these terms of use. If you do not agree, please do not use the application.

## 2. Service Description

Cybrief is a cybersecurity intelligence application that provides daily summaries of security alerts and threats, generated by artificial intelligence from public sources.

## 3. Subscription and Payment

**Free tier**: 5 articles per day, limited access to technical details.

**Premium**: unlimited access, full CVE details, IOCs, real-time critical alerts, newsletter.

Subscriptions are managed through the Apple App Store or Google Play Store. Current pricing is displayed in the app. All purchases are subject to the relevant platform's terms.

**Free trial**: 7 days, cancellable at any time before the trial ends without charge.

## 4. Intellectual Property

Summaries generated by Cybrief are provided for informational purposes. Original sources remain the property of their respective authors. Cybrief claims no rights over third-party content cited.

## 5. Limitation of Liability

Information provided by Cybrief is for informational purposes only and does not constitute professional security advice. Cybrief cannot be held liable for decisions made based on this information.

## 6. Changes to Terms

Cybrief reserves the right to modify these terms at any time. Users will be notified of significant changes through the application.

## 7. Contact

For any questions: **hello@cybrief.fr**
''';

  // ── Politique de confidentialité FR ──────────────────────────────────────

  static const String _privacyFr = '''
**Dernière mise à jour : mai 2026**

## 1. Données collectées

Cybrief collecte les données suivantes :

- **Compte** : adresse e-mail, nom d'affichage (lors de l'inscription)
- **Utilisation** : articles consultés (pour le quota quotidien), préférences de notification
- **Technique** : token FCM (notifications push), langue préférée
- **Abonnement** : statut d'abonnement via RevenueCat (aucune donnée bancaire stockée par Cybrief)

## 2. Utilisation des données

Vos données sont utilisées pour :

- Authentifier votre compte (Firebase Authentication)
- Gérer votre abonnement et quota d'articles
- Envoyer des notifications push si vous les activez
- Envoyer la newsletter si vous y souscrivez
- Améliorer l'application (statistiques anonymes d'utilisation)

## 3. Partage des données

Vos données ne sont **jamais vendues** à des tiers. Elles peuvent être transmises à :

- **Firebase (Google)** : authentification et notifications push
- **RevenueCat** : gestion des abonnements
- **Resend** : envoi de la newsletter (e-mail uniquement)
- **Railway** : hébergement du backend (données chiffrées en transit)

## 4. Conservation des données

Vos données sont conservées tant que votre compte est actif. Vous pouvez demander la suppression de votre compte et de toutes vos données à **hello@cybrief.fr**.

## 5. Vos droits (RGPD)

Conformément au RGPD, vous disposez des droits d'accès, de rectification, d'effacement, de portabilité et d'opposition. Pour exercer ces droits : **hello@cybrief.fr**

## 6. Cookies et tracking

L'application mobile ne dépose pas de cookies. Aucun tracking publicitaire n'est effectué.

## 7. Sécurité

Les données sont chiffrées en transit (HTTPS/TLS). Les mots de passe ne sont jamais stockés en clair (gestion déléguée à Firebase Auth).

## 8. Contact

Responsable du traitement : **Cybrief — hello@cybrief.fr**
''';

  // ── Privacy Policy EN ────────────────────────────────────────────────────

  static const String _privacyEn = '''
**Last updated: May 2026**

## 1. Data Collected

Cybrief collects the following data:

- **Account**: email address, display name (upon registration)
- **Usage**: articles viewed (for daily quota), notification preferences
- **Technical**: FCM token (push notifications), preferred language
- **Subscription**: subscription status via RevenueCat (no banking data stored by Cybrief)

## 2. Use of Data

Your data is used to:

- Authenticate your account (Firebase Authentication)
- Manage your subscription and article quota
- Send push notifications if you enable them
- Send the newsletter if you subscribe
- Improve the app (anonymous usage statistics)

## 3. Data Sharing

Your data is **never sold** to third parties. It may be shared with:

- **Firebase (Google)**: authentication and push notifications
- **RevenueCat**: subscription management
- **Resend**: newsletter delivery (email only)
- **Railway**: backend hosting (data encrypted in transit)

## 4. Data Retention

Your data is retained as long as your account is active. You can request deletion of your account and all your data at **hello@cybrief.fr**.

## 5. Your Rights (GDPR)

Under GDPR, you have the right to access, rectification, erasure, portability, and objection. To exercise these rights: **hello@cybrief.fr**

## 6. Cookies and Tracking

The mobile app does not use cookies. No advertising tracking is performed.

## 7. Security

Data is encrypted in transit (HTTPS/TLS). Passwords are never stored in plain text (delegated to Firebase Auth).

## 8. Contact

Data controller: **Cybrief — hello@cybrief.fr**
''';
}

// ── Simple markdown-like renderer ─────────────────────────────────────────

class _LegalContent extends StatelessWidget {
  final String markdown;
  const _LegalContent({required this.markdown});

  @override
  Widget build(BuildContext context) {
    final lines = markdown.trim().split('\n');
    final widgets = <Widget>[];

    for (final line in lines) {
      if (line.startsWith('## ')) {
        widgets.add(const SizedBox(height: 20));
        widgets.add(Text(line.substring(3), style: GoogleFonts.inter(
          fontSize: 16, fontWeight: FontWeight.w700, color: Colors.white,
        )));
        widgets.add(const SizedBox(height: 8));
      } else if (line.startsWith('**') && line.endsWith('**')) {
        widgets.add(Text(line.replaceAll('**', ''), style: GoogleFonts.inter(
          fontSize: 13, fontWeight: FontWeight.w600,
          color: Colors.white.withValues(alpha: 0.7),
        )));
        widgets.add(const SizedBox(height: 8));
      } else if (line.startsWith('- ')) {
        widgets.add(Padding(
          padding: const EdgeInsets.only(left: 12, bottom: 4),
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text('• ', style: GoogleFonts.inter(
                fontSize: 14, color: const Color(0xFF38BDF8),
              )),
              Expanded(child: _buildRichLine(line.substring(2))),
            ],
          ),
        ));
      } else if (line.trim().isEmpty) {
        widgets.add(const SizedBox(height: 8));
      } else {
        widgets.add(_buildRichLine(line));
        widgets.add(const SizedBox(height: 4));
      }
    }

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: widgets,
    );
  }

  Widget _buildRichLine(String text) {
    final spans = <InlineSpan>[];
    final parts = text.split('**');
    for (int i = 0; i < parts.length; i++) {
      if (parts[i].isEmpty) continue;
      if (i.isOdd) {
        spans.add(TextSpan(
          text: parts[i],
          style: GoogleFonts.inter(fontSize: 14, fontWeight: FontWeight.w600, color: Colors.white),
        ));
      } else {
        spans.add(TextSpan(
          text: parts[i],
          style: GoogleFonts.inter(fontSize: 14, color: Colors.white.withValues(alpha: 0.75), height: 1.6),
        ));
      }
    }
    return RichText(text: TextSpan(children: spans));
  }
}
